// Probability validation utilities.
// These functions are deliberately pure: they never create or alter predictions.
// Use them only on genuinely out-of-sample predictions.

export type ThreeWaySample = { probHome: number; probDraw: number; probAway: number; outcome: 0 | 1 | 2 };
export type CalibrationBucket = { lower: number; upper: number; count: number; meanProbability: number; observedRate: number };
export type TopProbabilityCalibration = { ece: number | null; mce: number | null; buckets: CalibrationBucket[] };
const clamp01 = (v: number) => Math.max(0, Math.min(1, v));
export function isFiniteThreeWaySample(s: ThreeWaySample): boolean {
  return Number.isFinite(s.probHome) && Number.isFinite(s.probDraw) && Number.isFinite(s.probAway) &&
    s.probHome >= 0 && s.probDraw >= 0 && s.probAway >= 0 &&
    s.probHome + s.probDraw + s.probAway > 0;
}
function normalize3(a: number, b: number, c: number): [number, number, number] { const x = Math.max(0, a), y = Math.max(0, b), z = Math.max(0, c), sum = x + y + z; if (sum <= 0) return [1 / 3, 1 / 3, 1 / 3]; return [x / sum, y / sum, z / sum]; }
export function multiclassBrier(samples: ThreeWaySample[]): number | null { const valid = samples.filter(isFiniteThreeWaySample); if (!valid.length) return null; let total = 0; for (const s of valid) { const [h,d,a] = normalize3(s.probHome,s.probDraw,s.probAway); total += (h-(s.outcome===0?1:0))**2+(d-(s.outcome===1?1:0))**2+(a-(s.outcome===2?1:0))**2; } return total/valid.length; }
export function multiclassLogLoss(samples: ThreeWaySample[]): number | null { const valid = samples.filter(isFiniteThreeWaySample); if (!valid.length) return null; const EPS=1e-15; let total = 0; for (const s of valid) { const [h,d,a] = normalize3(s.probHome,s.probDraw,s.probAway); total -= Math.log(Math.max(EPS,s.outcome===0?h:s.outcome===1?d:a)); } return total/valid.length; }
export function reliabilityBuckets(samples: ThreeWaySample[], selector:(s:ThreeWaySample)=>number, outcome:0|1|2, bucketCount=10):CalibrationBucket[]{ const n=Math.max(2,Number.isFinite(bucketCount)?Math.floor(bucketCount):10); const buckets=Array.from({length:n},(_,i)=>({lower:i/n,upper:(i+1)/n,rows:[] as {p:number;hit:boolean}[]})); for(const s of samples){if(!isFiniteThreeWaySample(s))continue;const p=clamp01(selector(s));if(!Number.isFinite(p))continue;const index=Math.max(0,Math.min(n-1,Math.floor(p*n)));buckets[index].rows.push({p,hit:s.outcome===outcome});} return buckets.map(b=>({lower:b.lower,upper:b.upper,count:b.rows.length,meanProbability:b.rows.length?b.rows.reduce((sum,r)=>sum+r.p,0)/b.rows.length:0,observedRate:b.rows.length?b.rows.filter(r=>r.hit).length/b.rows.length:0})); }
export function topProbabilityCalibration(samples: ThreeWaySample[], bucketCount=10):TopProbabilityCalibration { const valid=samples.filter(isFiniteThreeWaySample); if(!valid.length)return{ece:null,mce:null,buckets:[]}; const n=Math.max(2,Number.isFinite(bucketCount)?Math.floor(bucketCount):10); const buckets=Array.from({length:n},(_,i)=>({lower:i/n,upper:(i+1)/n,rows:[] as {p:number;hit:boolean}[]})); for(const s of valid){const probs=[clamp01(s.probHome),clamp01(s.probDraw),clamp01(s.probAway)];const index=probs[0]>=probs[1]&&probs[0]>=probs[2]?0:probs[1]>=probs[2]?1:2;const p=probs[index];const bucketIndex=Math.max(0,Math.min(n-1,Math.floor(p*n)));buckets[bucketIndex].rows.push({p,hit:s.outcome===index});} const normalized=buckets.map(b=>({lower:b.lower,upper:b.upper,count:b.rows.length,meanProbability:b.rows.length?b.rows.reduce((sum,r)=>sum+r.p,0)/b.rows.length:0,observedRate:b.rows.length?b.rows.filter(r=>r.hit).length/b.rows.length:0}));const total=valid.length;const gaps=normalized.filter(b=>b.count>0).map(b=>Math.abs(b.meanProbability-b.observedRate));const ece=normalized.reduce((sum,b)=>sum+(b.count/total)*Math.abs(b.meanProbability-b.observedRate),0);return{ece,mce:gaps.length?Math.max(...gaps):null,buckets:normalized}; }
export function shrinkTowardBaseRate(probability:number,baseRate:number,effectiveSample:number,priorStrength=50):number{const p=clamp01(probability),b=clamp01(baseRate),n=Math.max(0,effectiveSample),prior=Math.max(1,priorStrength);return clamp01((p*n+b*prior)/(n+prior));}
export function validateThreeWay(samples:ThreeWaySample[],minimumSamples=100):{sample:number;sufficientSample:boolean;brier:number|null;logLoss:number|null}{const valid=samples.filter(isFiniteThreeWaySample);return{sample:valid.length,sufficientSample:valid.length>=minimumSamples,brier:multiclassBrier(valid),logLoss:multiclassLogLoss(valid)};}
